apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/mmorhun/pr-test-components?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "component1-nudging"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: nudge-app
    appstudio.openshift.io/component: component1-nudging
    pipelines.appstudio.openshift.io/type: build
  name: component1-nudging-on-pull-request
  namespace: mmorhun-tenant
spec:
  pipelineSpec:
    tasks:
    - name: apply-tags
      params:
      - name: IMAGE_URL
        value: quay.io/rhacs-eng/konflux-tasks-trust
      - name: IMAGE_DIGEST
        value: sha256:9cd3213dc47ff3fe811797624df0fbdbec536c856a34220d2412381d418cc964
      - name: ADDITIONAL_TAGS
        value: ["new-tag"]
      taskRef:
        params:
        - name: name
          value: apply-tags
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.2@sha256:730ebb3df6c676675de1e12e1134be9298ed94afde5bba562ba2a50be1b6d7fd
        - name: kind
          value: task
        resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-component1-nudging
